name: Build and Analyze

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r app/requirements.txt

    - name: Run tests and SonarQube analysis
      run: |
        pytest
        sonar-scanner -Dsonar.projectKey=proyecto-si8811a -Dsonar.organization=upt-faing-epis -Dsonar.token=${{ secrets.sonar }}

    - name: Security scans
      run: |
        snyk test
        semgrep --config .semgrep.yml
