name: Build, Push Docker Image, and Create Release

on:
  push:
    tags:
      - 'v*'  # Se activará cuando se empuje un tag que empiece con 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image to GitHub Packages
      uses: docker/build-push-action@v3
      with:
        context: ./app
        push: true
        file: ./app/Dockerfile  # Cambia si tu Dockerfile está en otro lugar
        tags: ghcr.io/upt-faing-epis/proyecto-si8811a-2024-ii-u2-api-y-funciones-meza-y-castaneda/login_api:${{ github.ref_name }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./app/Dockerfile  # Puedes añadir otros archivos si los necesitas
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify Docker image from GitHub Packages
      run: |
        docker pull ghcr.io/upt-faing-epis/proyecto-si8811a-2024-ii-u2-api-y-funciones-meza-y-castaneda/login_api:${{ github.ref_name }}
