name: Build, Push Docker Image, and Create Release

on:
  push:
    branches:
      - main  # Puedes cambiar a la rama que desees

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image to GitHub Packages
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        file: ./app/Dockerfile  # Cambia si tu Dockerfile está en otro lugar
        tags: ghcr.io/upt-faing-epis/proyecto-si8811a-2024-ii-u2-api-y-funciones-meza-y-castaneda/login_api:latest

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./app/Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify Docker image from GitHub Packages
      run: |
        docker pull ghcr.io/upt-faing-epis/proyecto-si8811a-2024-ii-u2-api-y-funciones-meza-y-castaneda/login_api:latest
